<ips:template parameters="$time, $memory, $files, $templates, $database, $cache, $logs, $extra, $info, $environment, $debug, $executions"/>
<div id="dtProfilerBarContainer" class="dtProfilerBar">
    <ul class="ipsList_reset dtProfilerBar_list ipsClearfix" data-ipsdtprofiler{{if settings.dtprofiler_enable_debug && settings.dtprofiler_enable_debug_ajax }} data-ipsdtprofilerdebug data-url="{url='app=toolbox&module=bt&controller=bt' base='front'}"{{endif}}>
        {{if $time }}
        <li id="elProfileTimeLog" title="total time" class="isParent dtProfileFirst dtProfilerTime" data-ipstooltip>
            <i class="fa fa-server"></i> {$time['total']}ms <i class="fa fa-angle-up dtprofilearrow"></i>
        </li>
        <ul id="elProfileTimeLog_list" class="ipsList_reset ipsHide dtProfilerBar_cache">
            <li>
                <a>
                    Complete Execution: {$time['total']}ms
                </a>
            </li>
            <li>
                <a>
                    Framework Execution: {$time['framework']}ms
                </a>
            </li>
            <li>
                <a>
                    Profiler Execution: {$time['profiler']}ms
                </a>
            </li>
        </ul>
        {{endif}}

        {{if $executions }}
        {$executions|raw}
        {{endif}}

        {{if $memory }}
        {$memory|raw}
        {{endif}}

        {{if $files }}
        {$files|raw}
        {{endif}}

        {{if $database }}
        {$database|raw}
        {{endif}}

        {{if $cache }}
        {$cache|raw}
        {{endif}}

        {{if $environment }}
        {$environment|raw}
        {{endif}}

        {{if $templates }}
        {$templates|raw}
        {{endif}}

        {{if $logs }}
        {$logs|raw}
        {{endif}}

        {{if $debug }}
        {$debug|raw}
        {{endif}}

        {{if $extra }}
        {$extra|raw}
        {{endif}}
    </ul>
    {{if $info }}
    <div class="dtProfilerInfoBar">
        {{foreach $info['other'] as $key => $inf }}
        <div>{$key} : {$inf|raw}</div>
        {{endforeach}}
        <div class="dtProfilerInfoBarPanel">
            <a id="elProfileSystem" href="#elProfileSystem_menu" title="System" class=" " data-ipstooltip data-ipsmenu>
                System <i class="fa fa-angle-up"></i>
            </a>
            <ul id="elProfileSystem_menu" class="ipsMenu ipsMenu_auto ipsMenu_wide ipsList_reset ipsHide">
                {{foreach $info['server'] as $key => $val }}
                <li class="ipsMenu_item">
                    {$val|raw}
                </li>
                {{endforeach}}
            </ul>

            <a href="{$info['cache']}">Clear Caches</a>

            <a href="#toolbox_snippet_menu" id="toolbox_snippet" data-ipsMenu>
                snippets
            </a>
            <ul id="toolbox_snippet_menu" class="ipsMenu ipsList_reset ipsHide">
                <li class="ipsMenu_item">
                    <a href="{url="app=toolbox&module=bt&controller=bt&do=lorem"}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsDialog-remoteSubmit="true" data-ipsdialog-title="Lorem Ipsum Generator">
                        Lorem Ipsum
                    </a>
                </li>
                <li class="ipsMenu_item">
                    <a href="{url="app=toolbox&module=bt&controller=bt&do=bitwiseValues"}" data-ipsDialog data-ipsdialog-title="BitWise Values">
                        BitWise Values
                    </a>
                </li>
            </ul>
            <a href="#" data-ipstoolboxproxy>
                Proxy Class
            </a>

            {{if isset( $info['sources']) }}
            <a id="elProfileSources" href="#elProfileSources_menu" title="Sources" class=" " data-ipstooltip data-ipsmenu>
                Sources <i class="fa fa-angle-up"></i>
            </a>
            <ul id="elProfileSources_menu" class="ipsMenu ipsMenu_auto ipsMenu_wide ipsList_reset ipsHide">
                {{foreach $info['sources'] as $key => $val }}
                <li class="ipsMenu_item">
                     <a href="{$val['url']}" data-ipsDialog data-ipsDialog-destructOnClos="true">
                         {$val['name']}
                     </a>
                </li>
                {{endforeach}}
            </ul>
            {{endif}}
        </div>
        {{if settings.dtprofiler_git_data || settings.dtprofiler_show_changes}}
        <div id="el_dtProfileGit" class="dttProfilerInfoGit ipsClearfix" data-ipsdtprofilergit data-ipsdtprofilergit-url="{$info['git_url']}">
            <div class="dttProfilerInfoGitLoading ipsLoading ipsLoading_tiny"></div>
        </div>
        {{endif}}
    </div>
    {{endif}}
</div>
<div class="dtProfilerPlaceHolder">
</div>
