//<?php namespace toolbox_IPS_cms_extensions_core_DesignersMode_Cms_a810a30411c5350adfe2b42d0727e90b5;

/* To prevent PHP errors (extending class does not exist) revealing path */

use const IPS\ROOT_PATH;

if (!\defined('\IPS\SUITE_UNIQUE_KEY')) {
    exit;
}

class toolbox_hook_cmsDesignerMode extends _HOOK_CLASS_
{
    public function toBuild()
    {
        if (defined('DT_THEME') && defined('DT_THEME_ID') && DT_THEME === true && DT_THEME_ID !== 0) {
            $path = ROOT_PATH . '/themes/cms/';
            if (file_exists($path)) {
                return false;
            }
        }

        return parent::toBuild(); // TODO: Change the autogenerated stub
    }

}
