//<?php namespace toolbox_IPS_Theme_Dev_Theme_afcc5c2b0a1f633008ea23a3d93c885d0;

/* To prevent PHP errors (extending class does not exist) revealing path */
if (!\defined('\IPS\SUITE_UNIQUE_KEY')) {
    exit;
}

class toolbox_hook_DevTheme extends _HOOK_CLASS_
{

    protected static function _getCssPath($app, $location = null, $path = null)
    {
        if( defined('DT_THEME') && defined('DT_THEME_ID') && DT_THEME === true && DT_THEME_ID !== 0) {
            //$this->sourceFolder = \IPS\ROOT_PATH . '/themes/28/html/' . $app . '/' . $templateLocation . '/' . $templateName . '/';
            $themedir = \IPS\ROOT_PATH . '/themes/' . \IPS\toolbox\Application::getThemeId(
                ) . '/css/' . $app . '/' . $location . '/' . $path . '/';
            $return = rtrim($themedir, '/') . (\stristr($path, '.css') ? '' : '/');
            return $return;
        }

        return parent::_getCssPath($app, $location, $path); // TODO: Change the autogenerated stub
    }

    protected static function _getHtmlPath($app, $location = null, $path = null)
    {
        if( defined('DT_THEME') && defined('DT_THEME_ID') && DT_THEME === true && DT_THEME_ID !== 0) {
            //$this->sourceFolder = \IPS\ROOT_PATH . '/themes/28/html/' . $app . '/' . $templateLocation . '/' . $templateName . '/';
            $themedir = \IPS\ROOT_PATH . '/themes/' . \IPS\toolbox\Application::getThemeId(
                ) . '/html/' . $app . '/' . $location . '/';

            return rtrim($themedir, '/');
        }
        return parent::_getHtmlPath($app, $location, $path); // TODO: Change the autogenerated stub
    }

    protected static function _getResourcePath($app, $location = null, $path = null)
    {
        if( defined('DT_THEME') && defined('DT_THEME_ID') && DT_THEME === true && DT_THEME_ID !== 0) {
            if ($app == 'core' and $location == 'global' and mb_substr($path, 0, mb_strpos($path, '/')) === 'plugins') {
                foreach (
                    new \GlobIterator(
                        \IPS\ROOT_PATH . '/plugins/*/dev/resources/' . mb_substr($path, mb_strpos($path, '/') + 1)
                    ) as $file
                ) {
                    return $file->getPathName();
                }
            }

            return rtrim(
                    \IPS\ROOT_PATH . '/themes/' . \IPS\toolbox\Application::getThemeId(
                    ) . '/resources/' . $app . '/' . $location . '/' . $path,
                    '/'
                ) . ((\stristr($path, '.') || \stristr($path, '{')) ? '' : '/');
        }

        return parent::_getResourcePath($app, $location, $path);
    }

    public function css($file, $app = null, $location = null)
    {
        $loc = \IPS\Dispatcher::hasInstance() ? \IPS\Dispatcher::i()->controllerLocation : null;

        $return = parent::css($file, $app, $location);
        if( defined('DT_THEME') && defined('DT_THEME_ID') && DT_THEME === true && DT_THEME_ID !== 0) {
            $new = [];
            foreach ($return as $k => $v) {

                $link = str_replace(
                    'applications/core/interface/css/css.php',
                    'applications/toolbox/interface/css/css.php',
                    $v
                );

                if( $loc === 'admin'){
                    $link .= '&admin=1';
                }

                $new[$k] = $link;
            }

            $return = $new;
        }

        return $return;
    }
}
