//<?php namespace toolbox_IPS_Helpers_Table_Custom_ac16e012da1288a7da21c27bc8228cc63;

/* To prevent PHP errors (extending class does not exist) revealing path */
if ( !\defined( '\IPS\SUITE_UNIQUE_KEY' ) )
{
	exit;
}

class toolbox_hook_HelpersTableCustom extends _HOOK_CLASS_
{

    public function __toString()
    {
        if( $this->langPrefix === 'database_column_'){
            $this->rootButtons['addMulti'] = array(
                    'icon'	=> 'plus',
                    'title'	=> 'database_columns_add',
                    'link'	=> '#',
                    'data'	=> array( 'ipsDialog' => '', 'ipsDialog-title' => \IPS\Member::loggedIn()->language()->addToStack('database_columns_add') )
            );
        }
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}
