//<?php

/* To prevent PHP errors (extending class does not exist) revealing path */
if ( !\defined( '\IPS\SUITE_UNIQUE_KEY' ) ) {
    exit;
}

class toolbox_hook_ipsLog extends _HOOK_CLASS_
{

    public static function debug( $message, $category = null )
    {

        if ( $category === 'request' ) {
            return;
        }

        return parent::debug( $message, $category ); // TODO: Change the autogenerated stub
    }

}
